parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: prueba
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: 762c78e871b19d986b5c6efb9fbdb2a91fd98d2c
    database_driver: pdo_mysql
    database_path: null
